### ISSUE TITLE
How can I select all .cs files?

### ISSUE THREAD

**Issue by MikeKholomeev** [Socolin/HighlightSpecialFiles#2]
How can I select all .cs files?

**Comment by Socolin** [comment]
Try `^.+\.cs$`

**Comment by MikeKholomeev** [comment]
Yea! Thanks, it helped.

I wonder - does it mean that regex pattern should match the whole file name?

**Comment by Socolin** [comment]
Yes, I think this is how Java regex works, I'll check later the details

**Comment by Socolin** [comment]
So yes, this is how `Pattern` work in java 

There is another method `hitEnd()` that do the partial match, since there is an easy workaround I think I'll let this that way.
